import { Product, Testimonial, Color, Material } from './types';

// Cyber-Luxe color options
export const CYBER_COLORS: Color[] = [
  { name: 'Cyan', hex: '#00D4FF', label: 'Cyan' },
  { name: 'Purple', hex: '#7C3AED', label: 'Purple' },
  { name: 'Magenta', hex: '#FF006E', label: 'Magenta' },
  { name: 'Amber', hex: '#FBBF24', label: 'Amber' },
  { name: 'Dark', hex: '#1A1A2E', label: 'Dark' },
];

// Materials available
export const MATERIALS_LIST: Material[] = [
  { id: 'pla', name: 'PLA', description: 'Standard, affordable, great for starters', priceAddon: 0 },
  { id: 'petg', name: 'PETG', description: 'Durable, resistant to chemicals', priceAddon: 5 },
  { id: 'nylon', name: 'Nylon', description: 'Premium, flexible, strongest', priceAddon: 15 },
];

// Mock products (15 total: 3 featured, 5 ponçage, 4 aspiration, 3 essentiels)
export const PRODUCTS: Product[] = [
  // Featured products
  {
    id: 'product-001',
    name: 'Grip Ergonomique Pro',
    description: 'Poignée premium pour meuleuses, designed pour confort maximal lors d\'usage prolongé',
    price: 49.99,
    category: 'ponçage',
    image: '/products/grip-pro.jpg',
    colors: [CYBER_COLORS[0], CYBER_COLORS[1], CYBER_COLORS[3]],
    materials: MATERIALS_LIST,
    featured: true,
    rating: 4.9,
    reviewCount: 127,
    tags: ['Best-seller', 'Ergonomique'],
  },
  {
    id: 'product-002',
    name: 'Collecteur d\'Air Compact',
    description: 'Système de collecte époustoufflant avec filtre haute-efficacité',
    price: 79.99,
    category: 'aspiration',
    image: '/products/air-collector.jpg',
    colors: [CYBER_COLORS[0], CYBER_COLORS[2]],
    materials: MATERIALS_LIST,
    featured: true,
    rating: 4.7,
    reviewCount: 89,
    tags: ['Nouveau', 'Tendance'],
  },
  {
    id: 'product-003',
    name: 'Kit Essentiel Artisan',
    description: 'Ensemble complet d\'accessoires pour débuter avec confidence',
    price: 129.99,
    category: 'essentiels',
    image: '/products/kit-essential.jpg',
    colors: [CYBER_COLORS[0], CYBER_COLORS[1]],
    materials: MATERIALS_LIST,
    featured: true,
    rating: 4.8,
    reviewCount: 156,
    tags: ['Best-seller', 'Complet'],
  },
  // Ponçage products (5 total, 3 more)
  {
    id: 'product-004',
    name: 'Pad Ponçage Micro',
    description: 'Tampon de ponçage ultra-fin pour finitions délicates',
    price: 19.99,
    category: 'ponçage',
    image: '/products/pad-micro.jpg',
    colors: [CYBER_COLORS[1], CYBER_COLORS[3]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.6,
    reviewCount: 42,
  },
  {
    id: 'product-005',
    name: 'Holder de Ponceuse',
    description: 'Porte-outil premium compatible avec tous modèles',
    price: 34.99,
    category: 'ponçage',
    image: '/products/holder-sander.jpg',
    colors: [CYBER_COLORS[0], CYBER_COLORS[2], CYBER_COLORS[3]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.5,
    reviewCount: 31,
  },
  {
    id: 'product-006',
    name: 'Support de Rotation',
    description: 'Plateau rotatif pour ponçage d\'angles difficiles',
    price: 44.99,
    category: 'ponçage',
    image: '/products/rotation-support.jpg',
    colors: [CYBER_COLORS[0]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.4,
    reviewCount: 28,
  },
  {
    id: 'product-007',
    name: 'Bac de Collecte',
    description: 'Réceptacle haute-capacité pour poussière',
    price: 29.99,
    category: 'ponçage',
    image: '/products/dust-bin.jpg',
    colors: [CYBER_COLORS[1], CYBER_COLORS[2]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.3,
    reviewCount: 35,
  },
  // Aspiration products (4 total, 3 more)
  {
    id: 'product-008',
    name: 'Tuyau Renforcé',
    description: 'Conduit haute-pression avec armature interne',
    price: 39.99,
    category: 'aspiration',
    image: '/products/hose-reinforced.jpg',
    colors: [CYBER_COLORS[0], CYBER_COLORS[3]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.7,
    reviewCount: 51,
  },
  {
    id: 'product-009',
    name: 'Filtre HEPA Pro',
    description: 'Élément filtrant haute-performance pour purification maximale',
    price: 24.99,
    category: 'aspiration',
    image: '/products/hepa-filter.jpg',
    colors: [CYBER_COLORS[1]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.8,
    reviewCount: 78,
  },
  {
    id: 'product-010',
    name: 'Adaptateur Universel',
    description: 'Connecteur compatible avec majorité des appareils',
    price: 14.99,
    category: 'aspiration',
    image: '/products/adapter-universal.jpg',
    colors: [CYBER_COLORS[0], CYBER_COLORS[1], CYBER_COLORS[2]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.2,
    reviewCount: 19,
  },
  {
    id: 'product-011',
    name: 'Station de Vidange',
    description: 'Système d\'extraction automatique pour poussière accumulée',
    price: 69.99,
    category: 'aspiration',
    image: '/products/drain-station.jpg',
    colors: [CYBER_COLORS[0]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.9,
    reviewCount: 63,
  },
  // Essentiels products (3 total)
  {
    id: 'product-012',
    name: 'Coffret Rangement XL',
    description: 'Boîte de stockage avec compartiments organisés',
    price: 59.99,
    category: 'essentiels',
    image: '/products/storage-box.jpg',
    colors: [CYBER_COLORS[1], CYBER_COLORS[3]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.6,
    reviewCount: 47,
  },
  {
    id: 'product-013',
    name: 'Lubrifiant Premium',
    description: 'Huile de maintenance haute-viscosité pour mécanismes',
    price: 17.99,
    category: 'essentiels',
    image: '/products/lubricant-premium.jpg',
    colors: [CYBER_COLORS[0]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.7,
    reviewCount: 91,
  },
  {
    id: 'product-014',
    name: 'Chiffon Microfibre',
    description: 'Tissu ultra-absorbant pour nettoyage délicat',
    price: 9.99,
    category: 'essentiels',
    image: '/products/microfiber-cloth.jpg',
    colors: [CYBER_COLORS[0], CYBER_COLORS[1]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.5,
    reviewCount: 102,
  },
  {
    id: 'product-015',
    name: 'Pack Sécurité Pro',
    description: 'Équipement de protection complète pour usage professionnel',
    price: 89.99,
    category: 'essentiels',
    image: '/products/safety-pack.jpg',
    colors: [CYBER_COLORS[2], CYBER_COLORS[3]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.8,
    reviewCount: 68,
  },
];

// Featured products for hero
export const FEATURED_PRODUCTS = PRODUCTS.filter(p => p.featured);

// Mock testimonials/UGC
export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-001',
    authorName: 'Marc Rousseau',
    authorTitle: 'Ébéniste Professionnel',
    quote: 'Les accessoires Addictive Prints ont révolutionné mon workflow. Précision impeccable et durabilité remarquable.',
    rating: 5,
    image: '/testimonials/marc.jpg',
  },
  {
    id: 'test-002',
    authorName: 'Sophie Martin',
    authorTitle: 'Artisan Bricolage',
    quote: 'Je suis impressionnée par la qualité. Le grip ergonomique fait vraiment la différence sur les longues sessions.',
    rating: 5,
    image: '/testimonials/sophie.jpg',
  },
  {
    id: 'test-003',
    authorName: 'Jean-Pierre Dubois',
    authorTitle: 'Restaurateur Mobilier',
    quote: 'Addictive Prints allie savoir-faire traditionnel et innovation. C\'est exactement ce que j\'attendais.',
    rating: 4,
    image: '/testimonials/jp.jpg',
  },
  {
    id: 'test-004',
    authorName: 'Nathalie Leroux',
    authorTitle: 'Menuisière',
    quote: 'Excellent rapport qualité-prix. Les matériaux sont vraiment premium et les finitions impeccables.',
    rating: 5,
    image: '/testimonials/nathalie.jpg',
  },
  {
    id: 'test-005',
    authorName: 'Thomas Petit',
    authorTitle: 'Sculpteur',
    quote: 'J\'utilise les produits depuis 6 mois. Zéro problème, performance constante. Très satisfait.',
    rating: 4,
    image: '/testimonials/thomas.jpg',
  },
  {
    id: 'test-006',
    authorName: 'Véronique Blanc',
    authorTitle: 'Charpentière',
    quote: 'Service client réactif, produits innovants, packaging premium. Je recommande sans hésiter.',
    rating: 5,
    image: '/testimonials/veronique.jpg',
  },
];
