import { Product, Testimonial, Color, Material } from './types';

// Stitch color options
export const STITCH_COLORS: Color[] = [
  { name: 'Sage', hex: '#becbb1', label: 'Sage Green' },
  { name: 'Olive', hex: '#88957d', label: 'Olive' },
  { name: 'Black', hex: '#131313', label: 'Black' },
  { name: 'Charcoal', hex: '#1f1f1f', label: 'Charcoal' },
  { name: 'Dark Gray', hex: '#2a2a2a', label: 'Dark Gray' },
  { name: 'Gray', hex: '#353535', label: 'Gray' },
  { name: 'Light Gray', hex: '#e2e2e2', label: 'Light Gray' },
  { name: 'Beige', hex: '#c5c7be', label: 'Beige' },
  { name: 'Taupe', hex: '#8f9289', label: 'Taupe' },
  { name: 'Dark Beige', hex: '#454840', label: 'Dark Beige' },
  { name: 'Khaki', hex: '#c2c9bc', label: 'Khaki' },
  { name: 'Forest', hex: '#56624d', label: 'Forest Green' },
];

// Materials available
export const MATERIALS_LIST: Material[] = [
  { id: 'pla', name: 'PLA', description: 'Standard, affordable, great for starters', priceAddon: 0 },
  { id: 'petg', name: 'PETG', description: 'Durable, resistant to chemicals', priceAddon: 5 },
  { id: 'nylon', name: 'Nylon', description: 'Premium, flexible, strongest', priceAddon: 15 },
];

// Mock products (15 total: 3 featured, 5 ponçage, 4 aspiration, 3 essentiels)
export const PRODUCTS: Product[] = [
  // Featured products
  {
    id: 'product-001',
    name: 'Grip Ergonomique Pro',
    description: 'Poignée premium pour meuleuses, designed pour confort maximal lors d\'usage prolongé',
    price: 49.99,
    category: 'ponçage',
    image: '/products/grip-pro.jpg',
    colors: [STITCH_COLORS[0], STITCH_COLORS[1], STITCH_COLORS[11]],
    materials: MATERIALS_LIST,
    featured: true,
    rating: 4.9,
    reviewCount: 127,
    tags: ['Best-seller', 'Ergonomique'],
    stock: 12,
    compatibility: ['Windows', 'macOS'],
  },
  {
    id: 'product-002',
    name: 'Collecteur d\'Air Compact',
    description: 'Système de collecte époustoufflant avec filtre haute-efficacité',
    price: 79.99,
    category: 'aspiration',
    image: '/products/air-collector.jpg',
    colors: [STITCH_COLORS[0], STITCH_COLORS[2]],
    materials: MATERIALS_LIST,
    featured: true,
    rating: 4.7,
    reviewCount: 89,
    tags: ['Nouveau', 'Tendance'],
    stock: 8,
    compatibility: ['Professional', 'Home'],
  },
  {
    id: 'product-003',
    name: 'Kit Essentiel Artisan',
    description: 'Ensemble complet d\'accessoires pour débuter avec confidence',
    price: 129.99,
    category: 'essentiels',
    image: '/products/kit-essential.jpg',
    colors: [STITCH_COLORS[0], STITCH_COLORS[1]],
    materials: MATERIALS_LIST,
    featured: true,
    rating: 4.8,
    reviewCount: 156,
    tags: ['Best-seller', 'Complet'],
    stock: 15,
    compatibility: ['3D Printers', 'CNC'],
  },
  // Ponçage products (5 total, 3 more)
  {
    id: 'product-004',
    name: 'Pad Ponçage Micro',
    description: 'Tampon de ponçage ultra-fin pour finitions délicates',
    price: 19.99,
    category: 'ponçage',
    image: '/products/pad-micro.jpg',
    colors: [STITCH_COLORS[1], STITCH_COLORS[11]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.6,
    reviewCount: 42,
    stock: 22,
    compatibility: ['Laser', 'Hobby'],
  },
  {
    id: 'product-005',
    name: 'Holder de Ponceuse',
    description: 'Porte-outil premium compatible avec tous modèles',
    price: 34.99,
    category: 'ponçage',
    image: '/products/holder-sander.jpg',
    colors: [STITCH_COLORS[0], STITCH_COLORS[2], STITCH_COLORS[11]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.5,
    reviewCount: 31,
    stock: 5,
    compatibility: ['Industrial', 'Workshop'],
  },
  {
    id: 'product-006',
    name: 'Support de Rotation',
    description: 'Plateau rotatif pour ponçage d\'angles difficiles',
    price: 44.99,
    category: 'ponçage',
    image: '/products/rotation-support.jpg',
    colors: [STITCH_COLORS[0]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.4,
    reviewCount: 28,
    stock: 18,
    compatibility: ['Windows', 'macOS'],
  },
  {
    id: 'product-007',
    name: 'Bac de Collecte',
    description: 'Réceptacle haute-capacité pour poussière',
    price: 29.99,
    category: 'ponçage',
    image: '/products/dust-bin.jpg',
    colors: [STITCH_COLORS[1], STITCH_COLORS[2]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.3,
    reviewCount: 35,
    stock: 0,
    compatibility: ['Professional', 'Home'],
  },
  // Aspiration products (4 total, 3 more)
  {
    id: 'product-008',
    name: 'Tuyau Renforcé',
    description: 'Conduit haute-pression avec armature interne',
    price: 39.99,
    category: 'aspiration',
    image: '/products/hose-reinforced.jpg',
    colors: [STITCH_COLORS[0], STITCH_COLORS[11]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.7,
    reviewCount: 51,
    stock: 14,
    compatibility: ['3D Printers', 'CNC'],
  },
  {
    id: 'product-009',
    name: 'Filtre HEPA Pro',
    description: 'Élément filtrant haute-performance pour purification maximale',
    price: 24.99,
    category: 'aspiration',
    image: '/products/hepa-filter.jpg',
    colors: [STITCH_COLORS[1]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.8,
    reviewCount: 78,
    stock: 25,
    compatibility: ['Laser', 'Hobby'],
  },
  {
    id: 'product-010',
    name: 'Adaptateur Universel',
    description: 'Connecteur compatible avec majorité des appareils',
    price: 14.99,
    category: 'aspiration',
    image: '/products/adapter-universal.jpg',
    colors: [STITCH_COLORS[0], STITCH_COLORS[1], STITCH_COLORS[2]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.2,
    reviewCount: 19,
    stock: 11,
    compatibility: ['Industrial', 'Workshop'],
  },
  {
    id: 'product-011',
    name: 'Station de Vidange',
    description: 'Système d\'extraction automatique pour poussière accumulée',
    price: 69.99,
    category: 'aspiration',
    image: '/products/drain-station.jpg',
    colors: [STITCH_COLORS[0]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.9,
    reviewCount: 63,
    stock: 6,
    compatibility: ['Windows', 'macOS'],
  },
  // Essentiels products (3 total)
  {
    id: 'product-012',
    name: 'Coffret Rangement XL',
    description: 'Boîte de stockage avec compartiments organisés',
    price: 59.99,
    category: 'essentiels',
    image: '/products/storage-box.jpg',
    colors: [STITCH_COLORS[1], STITCH_COLORS[11]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.6,
    reviewCount: 47,
    stock: 9,
    compatibility: ['Professional', 'Home'],
  },
  {
    id: 'product-013',
    name: 'Lubrifiant Premium',
    description: 'Huile de maintenance haute-viscosité pour mécanismes',
    price: 17.99,
    category: 'essentiels',
    image: '/products/lubricant-premium.jpg',
    colors: [STITCH_COLORS[0]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.7,
    reviewCount: 91,
    stock: 20,
    compatibility: ['3D Printers', 'CNC'],
  },
  {
    id: 'product-014',
    name: 'Chiffon Microfibre',
    description: 'Tissu ultra-absorbant pour nettoyage délicat',
    price: 9.99,
    category: 'essentiels',
    image: '/products/microfiber-cloth.jpg',
    colors: [STITCH_COLORS[0], STITCH_COLORS[1]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.5,
    reviewCount: 102,
    stock: 24,
    compatibility: ['Laser', 'Hobby'],
  },
  {
    id: 'product-015',
    name: 'Pack Sécurité Pro',
    description: 'Équipement de protection complète pour usage professionnel',
    price: 89.99,
    category: 'essentiels',
    image: '/products/safety-pack.jpg',
    colors: [STITCH_COLORS[2], STITCH_COLORS[11]],
    materials: MATERIALS_LIST,
    featured: false,
    rating: 4.8,
    reviewCount: 68,
    stock: 3,
    compatibility: ['Industrial', 'Workshop'],
  },
];

// Featured products for hero
export const FEATURED_PRODUCTS = PRODUCTS.filter(p => p.featured);

// Mock testimonials/UGC
export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-001',
    authorName: 'Marc Rousseau',
    authorTitle: 'Ébéniste Professionnel',
    quote: 'Les accessoires Addictive Prints ont révolutionné mon workflow. Précision impeccable et durabilité remarquable.',
    rating: 5,
    image: '/testimonials/marc.jpg',
  },
  {
    id: 'test-002',
    authorName: 'Sophie Martin',
    authorTitle: 'Artisan Bricolage',
    quote: 'Je suis impressionnée par la qualité. Le grip ergonomique fait vraiment la différence sur les longues sessions.',
    rating: 5,
    image: '/testimonials/sophie.jpg',
  },
  {
    id: 'test-003',
    authorName: 'Jean-Pierre Dubois',
    authorTitle: 'Restaurateur Mobilier',
    quote: 'Addictive Prints allie savoir-faire traditionnel et innovation. C\'est exactement ce que j\'attendais.',
    rating: 4,
    image: '/testimonials/jp.jpg',
  },
  {
    id: 'test-004',
    authorName: 'Nathalie Leroux',
    authorTitle: 'Menuisière',
    quote: 'Excellent rapport qualité-prix. Les matériaux sont vraiment premium et les finitions impeccables.',
    rating: 5,
    image: '/testimonials/nathalie.jpg',
  },
  {
    id: 'test-005',
    authorName: 'Thomas Petit',
    authorTitle: 'Sculpteur',
    quote: 'J\'utilise les produits depuis 6 mois. Zéro problème, performance constante. Très satisfait.',
    rating: 4,
    image: '/testimonials/thomas.jpg',
  },
  {
    id: 'test-006',
    authorName: 'Véronique Blanc',
    authorTitle: 'Charpentière',
    quote: 'Service client réactif, produits innovants, packaging premium. Je recommande sans hésiter.',
    rating: 5,
    image: '/testimonials/veronique.jpg',
  },
];
